- name: Create WordPress host persistent volume
  command: kubectl apply -f -
  args:
    stdin: "{{ lookup('template', 'wordpress_host_pv.yaml.j2') }}"
  register: wordpress_create_host_pv_result
  changed_when: >-
    wordpress_create_host_pv_result.stdout_lines
      | reject('match', '^.* unchanged$') | list | length > 0
